name: 01 - Building Blocks
on: 
  push:
    branches: main
  workflow_dispatch:
  
jobs:
  job1:
    name: echo-hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Say hello
        run: echo "Hello, World!"

  job2:
    name: echo-goodbye
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Failed step
        run: |
          echo "I will fail"
          exit 0

      - name: Say goodbye
        run: echo "Goodbye!"
      
 
